-- MySQL Script generated by MySQL Workbench
-- Sat Dec  9 17:30:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spring_boot_rest_api_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spring_boot_rest_api_db` ;

-- -----------------------------------------------------
-- Schema spring_boot_rest_api_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spring_boot_rest_api_db` DEFAULT CHARACTER SET utf8 ;
USE `spring_boot_rest_api_db` ;

-- -----------------------------------------------------
-- Table `spring_boot_rest_api_db`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spring_boot_rest_api_db`.`role` ;

CREATE TABLE IF NOT EXISTS `spring_boot_rest_api_db`.`role` (
  `role_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_rest_api_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spring_boot_rest_api_db`.`user` ;

CREATE TABLE IF NOT EXISTS `spring_boot_rest_api_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `role_role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_role_idx` (`role_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_role_id`)
    REFERENCES `spring_boot_rest_api_db`.`role` (`role_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_rest_api_db`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spring_boot_rest_api_db`.`permission` ;

CREATE TABLE IF NOT EXISTS `spring_boot_rest_api_db`.`permission` (
  `permission_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`permission_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_rest_api_db`.`role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spring_boot_rest_api_db`.`role_permission` ;

CREATE TABLE IF NOT EXISTS `spring_boot_rest_api_db`.`role_permission` (
  `role_permission_id` INT NOT NULL AUTO_INCREMENT,
  `role_role_id` INT NOT NULL,
  `permission_permission_id` INT NOT NULL,
  PRIMARY KEY (`role_permission_id`),
  INDEX `fk_role_permission_role1_idx` (`role_role_id` ASC) VISIBLE,
  INDEX `fk_role_permission_permission1_idx` (`permission_permission_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_permission_role1`
    FOREIGN KEY (`role_role_id`)
    REFERENCES `spring_boot_rest_api_db`.`role` (`role_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_role_permission_permission1`
    FOREIGN KEY (`permission_permission_id`)
    REFERENCES `spring_boot_rest_api_db`.`permission` (`permission_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_rest_api_db`.`note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spring_boot_rest_api_db`.`note` ;

CREATE TABLE IF NOT EXISTS `spring_boot_rest_api_db`.`note` (
  `note_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`note_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_rest_api_db`.`user_note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spring_boot_rest_api_db`.`user_note` ;

CREATE TABLE IF NOT EXISTS `spring_boot_rest_api_db`.`user_note` (
  `user_note_id` INT NOT NULL AUTO_INCREMENT,
  `user_user_id` INT NOT NULL,
  `note_note_id` INT NOT NULL,
  INDEX `fk_user_note_user1_idx` (`user_user_id` ASC) VISIBLE,
  INDEX `fk_user_note_note1_idx` (`note_note_id` ASC) VISIBLE,
  PRIMARY KEY (`user_note_id`),
  CONSTRAINT `fk_user_note_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `spring_boot_rest_api_db`.`user` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_user_note_note1`
    FOREIGN KEY (`note_note_id`)
    REFERENCES `spring_boot_rest_api_db`.`note` (`note_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
